---
- apt_key: id=49DE63CB url='http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0xC37BA5F849DE63CB'
- apt_repository: repo='ppa:blueboxgroup/openstack' update_cache=yes

# FIXME(cmt): for whatever reason the PPA doesnt like the signature on openvswitch-datapath-dkms
- apt: pkg=openvswitch-datapath-dkms force=yes

- apt: pkg={{ item }}
  with_items:
    - openvswitch-switch
    - vlan
    - bridge-utils


- template: src=etc/init/neutron-openvswitch-agent.conf dest=/etc/init/neutron-openvswitch-agent.conf

- service: name=neutron-openvswitch-agent state=started

# ovs_bridge: name=br-int state=present
- name: ovs int bridge
  shell: if ! ovs-vsctl br-exists br-int; then ovs-vsctl add-br br-int; fi

